### ISSUE TITLE
Training Weights File

### ISSUE THREAD

**Issue by LiuYustar** [long123524/CLCFormer#1]
Hello blogger, I want to test the WHU Building dataset directly with the weight file you have trained. I wonder if you can provide the training weight file for this dataset.

**Comment by yxzz1121** [comment]
AttributeError: 'list' object has no attribute 'view'

**Comment by long123524** [comment]
> AttributeError: 'list' object has no attribute 'view'

Maybe you only need to take out the first tensor in the tuple.

**Comment by long123524** [comment]
> Hello blogger, I want to test the WHU Building dataset directly with the weight file you have trained. I wonder if you can provide the training weight file for this dataset.

Thanks for you concern. Sorry, I have didn't find the weight file. You can train clcformer from scratch using your own cropped datasets.
